function getRegexValueForValidations(){
	var regexForValidation = new Object();
	regexForValidation.alphaNumWithDecimal=	new RegExp("^["+allowedAlphaCharSet+"0-9\\-\\. ]+$");
	regexForValidation.characterRegex=new RegExp("^["+allowedAlphaCharSet+" ]+$","i");
	regexForValidation.validBPName=new RegExp("^["+allowedAlphaCharSet+"0-9_,#:.)(&\\]\\[\\-\\s]*$");
	regexForValidation.validRuleName = new RegExp("^["+allowedAlphaCharSet+"0-9_\\- ]*$");
	regexForValidation.validName = new RegExp("^["+allowedAlphaCharSet+"& ]{1,30}$");
	regexForValidation.alphanum = new RegExp("^["+allowedAlphaCharSet+"0-9\\- ]+$","i");
	regexForValidation.personName = new RegExp("^(["+allowedAlphaCharSet+"]+([\\'](["+allowedAlphaCharSet+"])+)*)$","i");
	regexForValidation.validCommunicationName=new RegExp("^["+allowedAlphaCharSet+"0-9_\\- ]*$");
	regexForValidation.validLocation=new RegExp("^["+allowedAlphaCharSet+"0-9_\\-:\\\\.\\/ ]*$");
	regexForValidation.validBranchCode = new RegExp("^["+allowedAlphaCharSet+"0-9_]{1,20}$");
	regexForValidation.validNoteCode = new RegExp("^["+allowedAlphaCharSet+"0-9_]{1,20}$");
	regexForValidation.validCode = new RegExp("^["+allowedAlphaCharSet+"0-9_]{0,8}$");
	regexForValidation.validElementKey = new RegExp("^["+allowedAlphaCharSet+"0-9_\\-]+( ["+allowedAlphaCharSet+"0-9_\\-]+)*$");
	regexForValidation.validateDefaultRate = /^[0-9]{0,2}(\.[0-9]{1,2})?$|^(100)(\.[0]{1,2})?$/;
	regexForValidation.validateCurrConvRate = /^[0-9]*(\.[0-9]{0,12})?$/;
	regexForValidation.validateDefaultPercentage = /^[0-9]{0,2}(\.[0-9]{1,2})?$|^(100)(\.[0]{1,2})?$/;
	regexForValidation.validateLtv = /^[0-9]{0,2}(\.[0-9]{1,2})?$|^(100)(\.[0]{1,2})?$/;
	regexForValidation.validNameWithoutSpaces = new RegExp("^["+allowedAlphaCharSet+"0-9_]{1,20}$");
	regexForValidation.validTimecode = /^([01]?[0-9]|2[0-3]):[0-5][0-9]$/;
	regexForValidation.validInteger = /^-?\d+$/;
	regexForValidation.isoCode = /^[0-9+ ]+$/i;
	regexForValidation.amount = /^[0-9.,-]+$/i;
	regexForValidation.percent = /^[0-9]{0,2}(\.[0-9]{1,2})?$|^(100)(\.[0]{1,2})?$/i;
	regexForValidation.floatingDigits = /^[0-9]*(\.[0-9]+)?$/i;
	regexForValidation.dateDE = /^\d\d?\.\d\d?\.\d\d\d?\d?$/;
	regexForValidation.numberDE = /^-?(?:\d+|\d{1,3}(?:\.\d{3})+)(?:,\d+)?$/;
	regexForValidation.lettersOnly = new RegExp("^["+allowedAlphaCharSet+"]+$","i");
	regexForValidation.letterswithbasicpunc = new RegExp("^["+allowedAlphaCharSet+"\\-.,()'" + '\\"' +"\\s]+$","i");
	regexForValidation.parameterName = new RegExp("^["+allowedAlphaCharSet+"0-9_ ]+$");
	regexForValidation.eventcharCode = new RegExp("^["+allowedAlphaCharSet+"0-9_]+$");
	regexForValidation.validateRoleName=new RegExp("^["+allowedAlphaCharSet+"]["+allowedAlphaCharSet+"0-9_-]+$");
	regexForValidation.validateCharacterWithSpace = new RegExp('^[a-zA-Z," "]+$');
	regexForValidation.validateCharacterWithUnderscore = new RegExp('^[a-zA-Z,"_"]+$');
	return regexForValidation;
}